spring.datasource.url=jdbc:postgresql://localhost:5432/sga_asignacion
spring.datasource.username=us3r
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=dev
spring.security.user.password=dev123
